const colorTokens = require('../../../../tokens/tokens')

module.exports = {
  white: colorTokens.colors.white,
  black: colorTokens.colors.black,
  green_terminal: colorTokens.colors.terminal,
  brand: colorTokens.colors['brand-500'],

  green_light: colorTokens.colors['green-100'],
  green_superlight: colorTokens.colors['green-50'],
  green_hovered: colorTokens.colors['green-600'],
  green_active: colorTokens.colors['green-700'],

  red_light: colorTokens.colors['red-100'],
  red_superlight: colorTokens.colors['red-50'],
  red_hovered: colorTokens.colors['red-600'],
  red_active: colorTokens.colors['red-700'],
  
  orange_light: colorTokens.colors['orange-100'],
  orange_superlight: colorTokens.colors['orange-50'],
  orange_hovered: colorTokens.colors['orange-600'],
  orange_active: colorTokens.colors['orange-700'],
  
  blue_light: colorTokens.colors['blue-100'],
  blue_superlight: colorTokens.colors['blue-50'],
  blue_hovered: colorTokens.colors['blue-600'],
  blue_active: colorTokens.colors['blue-700'],
  
  green: colorTokens.colors['green-500'],
  blue: colorTokens.colors['blue-500'],
  orange: colorTokens.colors['orange-500'],
  red: colorTokens.colors['red-500'],
  yellow: colorTokens.colors['yellow-500'],
  purple: colorTokens.colors['purple-500'],
  magenta: colorTokens.colors['magenta-500'],
  /* Greyscale Light */
  grey_light: {
    '50': colorTokens.colors['grey-light-50'],
    '100': colorTokens.colors['grey-light-100'],
    '200': colorTokens.colors['grey-light-200'],
    '300': colorTokens.colors['grey-light-300'],
    '400': colorTokens.colors['grey-light-400'],
    '500': colorTokens.colors['grey-light-500'],
    '600': colorTokens.colors['grey-light-600'],
    '700': colorTokens.colors['grey-light-700'],
    '800': colorTokens.colors['grey-light-800'],
    '900': colorTokens.colors['grey-light-900'],
  },
  /* Grey Dark */
  grey_dark: {
    '50': colorTokens.colors['grey-dark-50'],
    '100': colorTokens.colors['grey-dark-100'],
    '200': colorTokens.colors['grey-dark-200'],
    '300': colorTokens.colors['grey-dark-300'],
    '400': colorTokens.colors['grey-dark-400'],
    '500': colorTokens.colors['grey-dark-500'],
    '600': colorTokens.colors['grey-dark-600'],
    '700': colorTokens.colors['grey-dark-700'],
    '800': colorTokens.colors['grey-dark-800'],
    '900': colorTokens.colors['grey-dark-900'], // black
  },
  /* Green */
  brand_scale: {
    '50': colorTokens.colors['brand-50'],
    '100': colorTokens.colors['brand-100'],
    '200': colorTokens.colors['brand-200'],
    '300': colorTokens.colors['brand-300'],
    '400': colorTokens.colors['brand-400'],
    '500': colorTokens.colors['brand-500'],
    '600': colorTokens.colors['brand-600'],
    '700': colorTokens.colors['brand-700'],
    '800': colorTokens.colors['brand-800'],
    '900': colorTokens.colors['brand-900'],
  },
  /* Green */
  green_scale: {
    '50': colorTokens.colors['green-50'],
    '100': colorTokens.colors['green-100'],
    '200': colorTokens.colors['green-200'],
    '300': colorTokens.colors['green-300'],
    '400': colorTokens.colors['green-400'],
    '500': colorTokens.colors['green-500'],
    '600': colorTokens.colors['green-600'],
    '700': colorTokens.colors['green-700'],
    '800': colorTokens.colors['green-800'],
    '900': colorTokens.colors['green-900'],
  },
  /* Blue */
  blue_scale: {
    '50': colorTokens.colors['blue-50'],
    '100': colorTokens.colors['blue-100'],
    '200': colorTokens.colors['blue-200'],
    '300': colorTokens.colors['blue-300'],
    '400': colorTokens.colors['blue-400'],
    '500': colorTokens.colors['blue-500'],
    '600': colorTokens.colors['blue-600'],
    '700': colorTokens.colors['blue-700'],
    '800': colorTokens.colors['blue-800'],
    '900': colorTokens.colors['blue-900'],
  },
  /* Orange */
  orange_scale: {
    '50': colorTokens.colors['orange-50'],
    '100': colorTokens.colors['orange-100'],
    '200': colorTokens.colors['orange-200'],
    '300': colorTokens.colors['orange-300'],
    '400': colorTokens.colors['orange-400'],
    '500': colorTokens.colors['orange-500'],
    '600': colorTokens.colors['orange-600'],
    '700': colorTokens.colors['orange-700'],
    '800': colorTokens.colors['orange-800'],
    '900': colorTokens.colors['orange-900'],
  },
  /* Red */
  red_scale: {
    '50': colorTokens.colors['red-50'],
    '100': colorTokens.colors['red-100'],
    '200': colorTokens.colors['red-200'],
    '300': colorTokens.colors['red-300'],
    '400': colorTokens.colors['red-400'],
    '500': colorTokens.colors['red-500'],
    '600': colorTokens.colors['red-600'],
    '700': colorTokens.colors['red-700'],
    '800': colorTokens.colors['red-800'],
    '900': colorTokens.colors['red-900'],
  },
  /* Yellow */
  yellow_scale: {
    '50': colorTokens.colors['yellow-50'],
    '100': colorTokens.colors['yellow-100'],
    '200': colorTokens.colors['yellow-200'],
    '300': colorTokens.colors['yellow-300'],
    '400': colorTokens.colors['yellow-400'],
    '500': colorTokens.colors['yellow-500'],
    '600': colorTokens.colors['yellow-600'],
    '700': colorTokens.colors['yellow-700'],
    '800': colorTokens.colors['yellow-800'],
    '900': colorTokens.colors['yellow-900'],
  },
  /* Purple */
  purple_scale: {
    '50': colorTokens.colors['purple-50'],
    '100': colorTokens.colors['purple-100'],
    '200': colorTokens.colors['purple-200'],
    '300': colorTokens.colors['purple-300'],
    '400': colorTokens.colors['purple-400'],
    '500': colorTokens.colors['purple-500'],
    '600': colorTokens.colors['purple-600'],
    '700': colorTokens.colors['purple-700'],
    '800': colorTokens.colors['purple-800'],
    '900': colorTokens.colors['purple-900'],
  },
  /* Magenta */
  magenta_scale: {
    '50': colorTokens.colors['magenta-50'],
    '100': colorTokens.colors['magenta-100'],
    '200': colorTokens.colors['magenta-200'],
    '300': colorTokens.colors['magenta-300'],
    '400': colorTokens.colors['magenta-400'],
    '500': colorTokens.colors['magenta-500'],
    '600': colorTokens.colors['magenta-600'],
    '700': colorTokens.colors['magenta-700'],
    '800': colorTokens.colors['magenta-800'],
    '900': colorTokens.colors['magenta-900'],
  },
  dark: {
    text: {
      primary: colorTokens.colors['dark-text-primary'],
      secondary: colorTokens.colors['dark-text-secondary'],
      tertiary: colorTokens.colors['dark-text-tertiary'],
      quaternary: colorTokens.colors['dark-text-quaternary'],
    },
    bg: {
      primary: colorTokens.colors['dark-bg-primary'],
      secondary: colorTokens.colors['dark-bg-secondary'],
      tertiary: colorTokens.colors['dark-bg-tertiary'],
      quaternary: colorTokens.colors['dark-bg-quaternary'],
    },
    border: {
      primary: colorTokens.colors['dark-border-primary'],
      secondary: colorTokens.colors['dark-border-secondary'],
      tertiary: colorTokens.colors['dark-border-tertiary'],
      quaternary: colorTokens.colors['dark-border-quaternary'],
    },
  },
  light: {
    text: {
      primary: colorTokens.colors['light-text-primary'],
      secondary: colorTokens.colors['light-text-secondary'],
      tertiary: colorTokens.colors['light-text-tertiary'],
      quaternary: colorTokens.colors['light-text-quaternary'],
    },
    bg: {
      primary: colorTokens.colors['light-bg-primary'],
      secondary: colorTokens.colors['light-bg-secondary'],
      tertiary: colorTokens.colors['light-bg-tertiary'],
      quaternary: colorTokens.colors['light-bg-quaternary'],
    },
    border: {
      primary: colorTokens.colors['light-border-primary'],
      secondary: colorTokens.colors['light-border-secondary'],
      tertiary: colorTokens.colors['light-border-tertiary'],
      quaternary: colorTokens.colors['light-border-quaternary'],
    },
  },
}
