const colorTokens = require('../../../../tokens/tokens.json')

module.exports = {
  white: '#ffffff',
  black: '#000000',
  custom_black: colorTokens.global.custom_black.value,
  green_primary: colorTokens.global.green_primary.value,
  green_terminal: colorTokens.global.green_terminal.value,
  green_classic: colorTokens.global.green_classic.value,
  green_hovered: colorTokens.global.Foundation.green.green_600.value,
  green_active: colorTokens.global.Foundation.green.green_700.value,
  green_light: colorTokens.global.Foundation.green.green_100.value,
  green_superlight: colorTokens.global.Foundation.green.green_50.value,
  green_dark_1: colorTokens.global.green_dark_1.value,
  green_dark_2: colorTokens.global.green_dark_2.value,
  red: colorTokens.global.red.value,
  red_light: colorTokens.global.red_light.value,
  red_hovered: colorTokens.global.Foundation.red.red_600.value,
  red_active: colorTokens.global.Foundation.red.red_700.value,
  red_superlight: colorTokens.global.Foundation.red.red_50.value,
  orange: colorTokens.global.orange.value,
  orange_light: colorTokens.global.orange_light.value,
  orange_hovered: colorTokens.global.Foundation.orange.orange_600.value,
  orange_active: colorTokens.global.Foundation.orange.orange_700.value,
  orange_superlight: colorTokens.global.Foundation.orange.orange_50.value,
  blue: colorTokens.global.blue.value,
  blue_light: colorTokens.global.blue_light.value,
  blue_hovered: colorTokens.global.Foundation.blue.blue_600.value,
  blue_active: colorTokens.global.Foundation.blue.blue_700.value,
  blue_superlight: colorTokens.global.Foundation.blue.blue_50.value,
  blue_pale: colorTokens.global.blue_pale.value,
  blue_grey: colorTokens.global.grey_blue_mid.value,
  purple: colorTokens.global.purple.value,
  purple_light: colorTokens.global.purple_light.value,
  yellow: colorTokens.global.yellow.value,
  magenta: colorTokens.global.magenta.value,
  /* Greyscale Light */
  greyscale_light_100: colorTokens.global.greyscale_light_100.value,
  greyscale_light_200: colorTokens.global.greyscale_light_200.value,
  greyscale_light_300: colorTokens.global.greyscale_light_300.value,
  greyscale_light_400: colorTokens.global.greyscale_light_400.value,
  greyscale_light_500: colorTokens.global.greyscale_light_500.value,
  greyscale_light_600: colorTokens.global.greyscale_light_600.value,
  greyscale_light_700: colorTokens.global.greyscale_light_700.value,
  greyscale_light_800: colorTokens.global.greyscale_light_800.value,
  /* Greyscale Dark */
  greyscale_dark_100: colorTokens.global.greyscale_dark_100.value,
  greyscale_dark_200: colorTokens.global.greyscale_dark_200.value,
  greyscale_dark_300: colorTokens.global.greyscale_dark_300.value,
  greyscale_dark_400: colorTokens.global.greyscale_dark_400.value,
  greyscale_dark_500: colorTokens.global.greyscale_dark_500.value,
  greyscale_dark_600: colorTokens.global.greyscale_dark_600.value,
  greyscale_dark_700: colorTokens.global.greyscale_dark_700.value,
  /* Green */
  green_ui_50: colorTokens.global.Foundation.green.green_50.value,
  green_ui_100: colorTokens.global.Foundation.green.green_100.value,
  green_ui_200: colorTokens.global.Foundation.green.green_200.value,
  green_ui_300: colorTokens.global.Foundation.green.green_300.value,
  green_ui_400: colorTokens.global.Foundation.green.green_400.value,
  green_ui_500: colorTokens.global.Foundation.green.green_500.value,
  green_ui_600: colorTokens.global.Foundation.green.green_600.value,
  green_ui_700: colorTokens.global.Foundation.green.green_700.value,
  green_ui_800: colorTokens.global.Foundation.green.green_800.value,
  green_ui_900: colorTokens.global.Foundation.green.green_900.value,
  /* Blue */
  blue_ui_50: colorTokens.global.Foundation.blue.blue_50.value,
  blue_ui_100: colorTokens.global.Foundation.blue.blue_100.value,
  blue_ui_200: colorTokens.global.Foundation.blue.blue_200.value,
  blue_ui_300: colorTokens.global.Foundation.blue.blue_300.value,
  blue_ui_400: colorTokens.global.Foundation.blue.blue_400.value,
  blue_ui_500: colorTokens.global.Foundation.blue.blue_500.value,
  blue_ui_600: colorTokens.global.Foundation.blue.blue_600.value,
  blue_ui_700: colorTokens.global.Foundation.blue.blue_700.value,
  blue_ui_800: colorTokens.global.Foundation.blue.blue_800.value,
  blue_ui_900: colorTokens.global.Foundation.blue.blue_900.value,
  /* Orange */
  orange_ui_50: colorTokens.global.Foundation.orange.orange_50.value,
  orange_ui_100: colorTokens.global.Foundation.orange.orange_100.value,
  orange_ui_200: colorTokens.global.Foundation.orange.orange_200.value,
  orange_ui_300: colorTokens.global.Foundation.orange.orange_300.value,
  orange_ui_400: colorTokens.global.Foundation.orange.orange_400.value,
  orange_ui_500: colorTokens.global.Foundation.orange.orange_500.value,
  orange_ui_600: colorTokens.global.Foundation.orange.orange_600.value,
  orange_ui_700: colorTokens.global.Foundation.orange.orange_700.value,
  orange_ui_800: colorTokens.global.Foundation.orange.orange_800.value,
  orange_ui_900: colorTokens.global.Foundation.orange.orange_900.value,
  /* Red */
  red_ui_50: colorTokens.global.Foundation.red.red_50.value,
  red_ui_100: colorTokens.global.Foundation.red.red_100.value,
  red_ui_200: colorTokens.global.Foundation.red.red_200.value,
  red_ui_300: colorTokens.global.Foundation.red.red_300.value,
  red_ui_400: colorTokens.global.Foundation.red.red_400.value,
  red_ui_500: colorTokens.global.Foundation.red.red_500.value,
  red_ui_600: colorTokens.global.Foundation.red.red_600.value,
  red_ui_700: colorTokens.global.Foundation.red.red_700.value,
  red_ui_800: colorTokens.global.Foundation.red.red_800.value,
  red_ui_900: colorTokens.global.Foundation.red.red_900.value,
  /* Yellow */
  yellow_ui_50: colorTokens.global.Foundation.yellow.yellow_50.value,
  yellow_ui_100: colorTokens.global.Foundation.yellow.yellow_100.value,
  yellow_ui_200: colorTokens.global.Foundation.yellow.yellow_200.value,
  yellow_ui_300: colorTokens.global.Foundation.yellow.yellow_300.value,
  yellow_ui_400: colorTokens.global.Foundation.yellow.yellow_400.value,
  yellow_ui_500: colorTokens.global.Foundation.yellow.yellow_500.value,
  yellow_ui_600: colorTokens.global.Foundation.yellow.yellow_600.value,
  yellow_ui_700: colorTokens.global.Foundation.yellow.yellow_700.value,
  yellow_ui_800: colorTokens.global.Foundation.yellow.yellow_800.value,
  yellow_ui_900: colorTokens.global.Foundation.yellow.yellow_900.value,
  /* Purple */
  purple_ui_50: colorTokens.global.Foundation.purple.purple_50.value,
  purple_ui_100: colorTokens.global.Foundation.purple.purple_100.value,
  purple_ui_200: colorTokens.global.Foundation.purple.purple_200.value,
  purple_ui_300: colorTokens.global.Foundation.purple.purple_300.value,
  purple_ui_400: colorTokens.global.Foundation.purple.purple_400.value,
  purple_ui_500: colorTokens.global.Foundation.purple.purple_500.value,
  purple_ui_600: colorTokens.global.Foundation.purple.purple_600.value,
  purple_ui_700: colorTokens.global.Foundation.purple.purple_700.value,
  purple_ui_800: colorTokens.global.Foundation.purple.purple_800.value,
  purple_ui_900: colorTokens.global.Foundation.purple.purple_900.value,
}
